// import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./dash.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootDashBoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-300">{children}</body>
    </html>
  );
}
